name: GracefulTransmission
version: '${version}'
main: io.hikarilan.gracefultransmission.GracefulTransmission
api-version: '1.13'
depend: [ProtocolLib]
authors: [HikariLan]
description: Provide amazing teleporting animation same as the GTA Online game
